name: "Setup CD workspace all in one"
description: "Setup tools and components for Cloud provider(Azure, AliCloud, etc.)"
branding:
  icon: cloud
  color: white
inputs:
  cloud-provider:
    description: 'cloud provider: Azure, AliCloud, TBD.'
    required: true
  azure-client-id:
    description: "OIDC client id to login Azure"
    required: false
  azure-tenant-id:
    description: "OIDC tenant id to login Azure"
    required: false
  azure-subscription-id:
    description: "OIDC subscription id to login Azure"
    required: false
  acr-login-registry:
    description: "Azure/AliCloud ACR registry to login"
    required: true
  acr-username:
    description: "Azure/AliCloud ACR username to login"
    required: true
  acr-password:
    description: "Azure/AliCloud ACR password to login"
    required: true
  azure-aks-resource-group:
    description: "Azure AKS cluster resource group"
    required: false
  azure-aks-cluster-name:
    description: "Azure AKS cluster name to use"
    required: false
  alicloud-ack-cluster-id:
    description: "AliCloud ACK cluster id to login"
    required: false
  alicloud-ack-access-key-id:
    description: "AliCloud access key id to login ACK"
    required: false
  alicloud-ack-access-key-secret:
    description: "AliCloud access key secret to login ACK"
    required: false
  need-cd-tools:
    description: "Whether to install CD tools: kubectl, skaffold, kustomize, helm, etc."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Check cloud-provider-1
      if: ${{ inputs.cloud-provider == '' }}
      shell: bash
      run: |
        echo "cloud-provider is required."
        exit 1
    - name: Check cloud-provider-2
      if: ${{ inputs.cloud-provider != 'AliCloud' && inputs.cloud-provider != 'Azure' }}
      shell: bash
      run: |
        echo "current cloud-provider is not supported."
        exit 1
    - name: Check AliCloud ACR parameters
      if: ${{ inputs.cloud-provider == 'AliCloud' && (inputs.acr-login-registry == '' || inputs.acr-username == '' || inputs.acr-password == '') }}
      shell: bash
      run: |
        echo "acr-login-registry, acr-username and acr-password are required."
        exit 1
    - name: Login to ACR Registry
      if: ${{ inputs.cloud-provider == 'AliCloud' }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.acr-login-registry }}
        username: ${{ inputs.acr-username }}
        password: ${{ inputs.acr-password }}
    - name: Check AliCloud ACK parameters
      if: ${{ inputs.cloud-provider == 'AliCloud' && (inputs.alicloud-ack-access-key-id == '' || inputs.alicloud-ack-access-key-secret == '' || inputs.alicloud-ack-cluster-id == '') }}
      shell: bash
      run: |
        echo "alicloud-ack-cluster-id, alicloud-ack-access-key-id and alicloud-ack-access-key-secret are required."
        exit 1
    - name: Set up kubeconfig for ACK cluster
      if: ${{ inputs.cloud-provider == 'AliCloud' }}
      uses: aliyun/ack-set-context@v1
      with:
        access-key-id: ${{ inputs.alicloud-ack-access-key-id }}
        access-key-secret: ${{ inputs.alicloud-ack-access-key-secret }}
        cluster-id: ${{ inputs.alicloud-ack-cluster-id }}
    - name: Check Azure Login parameters
      if: ${{ inputs.cloud-provider == 'Azure' && (inputs.azure-client-id == '' || inputs.azure-tenant-id == '' || inputs.azure-subscription-id == '') }}
      shell: bash
      run: |
        echo "Azure client-id, tenant-id, subscription-id are required."
        exit 1
    - uses: azure/login@v1
      if: ${{ inputs.cloud-provider == 'Azure' }}
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
    - name: Check Azure ACR parameters
      if: ${{ inputs.cloud-provider == 'Azure' && (inputs.acr-login-registry == '' || inputs.acr-username == '' || inputs.acr-password == '') }}
      shell: bash
      run: |
        echo "Azure ACR registry, username, password are required."
        exit 1
    - name: Login to ACR Registry
      if: ${{ inputs.cloud-provider == 'Azure' }}
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.acr-login-registry }}
        username: ${{ inputs.acr-username }}
        password: ${{ inputs.acr-password }}
    - name: Check Azure AKS parameters
      if: ${{ inputs.cloud-provider == 'Azure' && (inputs.azure-aks-resource-group == '' || inputs.azure-aks-cluster-name == '') }}
      shell: bash
      run: |
        echo "Azure AKS resource group, cluster name are required."
        exit 1
    - uses: azure/aks-set-context@v3
      if: ${{ inputs.cloud-provider == 'Azure' }}
      with:
        resource-group: ${{ inputs.azure-aks-resource-group }}
        cluster-name: ${{ inputs.azure-aks-cluster-name }}
        admin: true
    - uses: coscene-io/setup-cd-tools@v2.0.1
      if: ${{ inputs.need-cd-tools == 'true' }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      with:
        kubectl: '1.25.0'
        kustomize: '4.5.7'
        skaffold: '1.39.2'
        jq: '1.6'
        helm: '3.10.2'
